# Generated by Django 4.2.6 on 2025-08-06 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_pushsubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='pushsubscription',
            name='last_seen',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
